// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C: each takes the hook's session and the
// ticket of its call, and is called directly.
const root = @import("galley");
pub const Payload = struct {};

pub fn reduction(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction" }));
}
pub fn reduction_Start(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Start" }));
}
pub fn reduction_Items(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Items" }));
}
pub fn reduction_Item(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Item" }));
}
pub fn reduction_String(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_String" }));
}
pub fn reduction_LongString(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_LongString" }));
}
pub fn reduction_DashItem(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_DashItem" }));
}
pub fn reduction_BraceItems(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BraceItems" }));
}
pub fn reduction_ParenItems(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ParenItems" }));
}
pub fn reduction_BracketAfter(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BracketAfter" }));
}
pub fn reduction__LongStringContent(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__LongStringContent" }));
}
pub fn reduction__LineCommentTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__LineCommentTail" }));
}
pub fn reduction_BraceItem(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BraceItem" }));
}
pub fn reduction_ParenItem(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ParenItem" }));
}
pub fn reduction_BracketItems(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BracketItems" }));
}
pub fn reduction_BracketItem(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BracketItem" }));
}
pub fn reduction__DoubleStringContent(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__DoubleStringContent" }));
}
pub fn reduction__SingleStringContent(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__SingleStringContent" }));
}
pub fn reduction__LongStringAfterBracket(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__LongStringAfterBracket" }));
}
pub fn reduction__AugmentedStart(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__AugmentedStart" }));
}
pub fn reduction_GenerativeTerminal(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_GenerativeTerminal" }));
}
pub fn reduction_DashItem_Tail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_DashItem_Tail" }));
}
