// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C; they are called directly.
const root = @import("galley");
pub const Payload = struct {};

pub extern fn reduction(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Start(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Items(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Item(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_String(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_LongString(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_DashItem(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_BraceItems(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_ParenItems(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_BracketAfter(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__LongStringContent(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__LineCommentTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_BraceItem(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_ParenItem(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_BracketItems(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_BracketItem(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__DoubleStringContent(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__SingleStringContent(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__LongStringAfterBracket(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__AugmentedStart(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_GenerativeTerminal(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_DashItem_Tail(*root.data_structures.ProcedureArguments) void;
