/**
 * Bun procedure-dispatch installer.
 *
 * Owns the `JSCallback` that the shared JS shim
 * (`galley_install_js_dispatch_id`, generated by `@sanbus/galley-core/build/shim.mjs`)
 * forwards every parser hook through. The hook tables live in the core —
 * one per session; this module only bridges the native boundary, with one
 * callback closure per loaded library so two grammars in one process
 * never share a port or a name table. Libraries that predate integer
 * hook IDs still export the name-carrying `galley_install_js_dispatch`,
 * used as a fallback.
 */

import { createRequire } from "node:module";
import * as path from "node:path";
import { JSCallback, FFIType, toArrayBuffer } from "bun:ffi";

import { loadProceduresModule } from "@sanbus/galley-core";
import type { FfiPort } from "@sanbus/galley-core";
import type { BunPort } from "./ffi.ts";

const require = createRequire(import.meta.url);
const textDecoder = new TextDecoder();

// Held to prevent GC of the callbacks; installed per library path.
// ID and name paths keep separate slots: their signatures differ.
// Per-path (not singletons): each closure captures its own library's
// port and name table, so two grammars in one process never cross.
const idCallbacks = new Map<string, unknown>();
const idPointers = new Map<string, number>();
const nameCallbacks = new Map<string, unknown>();
const namePointers = new Map<string, number>();
const installedFor = new Set<string>();

/**
 * Synchronously loads the language directory's `procedures` module, if
 * any. Returns the module for the session to install into its own
 * registry; never touches another session's hooks.
 */
export function loadProcedures(languagePath: string): Record<string, unknown> | null {
  return loadProceduresModule(
    (specifier) => require(specifier) as unknown,
    path.join,
    languagePath,
  );
}

export function ensureDispatchFor(port: BunPort & FfiPort): void {
  if (!port.supportsDispatch) {
    // No dispatch — installs stay no-ops.
    return;
  }
  if (installedFor.has(port.libraryPath)) return;
  if (
    typeof port.native.galley_install_js_dispatch_id === "function" &&
    port.procedureNames().length > 0
  ) {
    installIdDispatch(port);
  } else {
    installNameDispatch(port);
  }
  installedFor.add(port.libraryPath);
}

function installIdDispatch(port: BunPort & FfiPort): void {
  // Integer hook IDs; unknown IDs are silent no-ops.
  const table = port.procedureNames();
  const cb = new JSCallback(
    (id: number, argsPtr: number) => {
      const name = table[id];
      if (name === undefined) return;
      port.activeDispatch?.(name, argsPtr);
    },
    { args: [FFIType.u32, FFIType.ptr], returns: FFIType.void },
  );
  // Prevent GC — the trampoline must stay reachable for the process lifetime.
  idCallbacks.set(port.libraryPath, cb);
  const pointer = cb.ptr as number;
  idPointers.set(port.libraryPath, pointer);
  try {
    (port.native.galley_install_js_dispatch_id as (callback: number) => void)(pointer);
  } catch {
    // Missing installer — stays no-op.
  }
}

function installNameDispatch(port: BunPort & FfiPort): void {
  // Callback takes (namePtr, nameLen, argsPtr); nameLen arrives as bigint.
  const cb = new JSCallback(
    (namePtr: number, nameLen: bigint, argsPtr: number) => {
      if (!namePtr) return;
      let name: string;
      try {
        const bytes = toArrayBuffer(namePtr, 0, Number(nameLen)) as ArrayBuffer;
        name = textDecoder.decode(bytes);
      } catch (e) {
        console.error("galley procedure dispatch: failed to decode name", e);
        return;
      }
      port.activeDispatch?.(name, argsPtr);
    },
    { args: [FFIType.ptr, FFIType.u64, FFIType.ptr], returns: FFIType.void },
  );
  // Prevent GC — the trampoline must stay reachable for the process lifetime.
  nameCallbacks.set(port.libraryPath, cb);
  const pointer = cb.ptr as number;
  namePointers.set(port.libraryPath, pointer);
  try {
    port.native.galley_install_js_dispatch(pointer);
  } catch {
    // Missing installer — stays no-op.
  }
}
