/**
 * Bun procedure-dispatch installer.
 *
 * Owns the `JSCallback` that the shared JS shim
 * (`galley_install_js_dispatch_id`, generated by `@sanbus/galley-core/build/shim.mjs`)
 * forwards every parser hook through, plus the `require()`-based auto-scan
 * of `procedures.*` in the language directory (Bun loads TypeScript
 * synchronously, like Node). The registry and the ID-to-name dispatcher
 * live in the core; this module only bridges the native boundary.
 * Libraries that predate integer hook IDs still export the name-carrying
 * `galley_install_js_dispatch`, used as a fallback.
 */

import { createRequire } from "node:module";
import * as path from "node:path";
import { JSCallback, FFIType, toArrayBuffer } from "bun:ffi";

import { dispatchProcedure, installProcedures, listProcedures } from "@sanbus/galley-core";
import type { FfiPort } from "@sanbus/galley-core";
import type { BunPort } from "./ffi.ts";

const require = createRequire(import.meta.url);
const textDecoder = new TextDecoder();

// Held to prevent GC of the callbacks; installed per library path.
// ID and name paths keep separate slots: their signatures differ.
let dispatchIdCallback: unknown = null;
let dispatchIdPointer: number | null = null;
let dispatchCallback: unknown = null;
let dispatchPointer: number | null = null;
const installedFor = new Set<string>();
let autoAttempted = false;

function isProcedureName(name: string): boolean {
  return name === "reduction" || name.startsWith("reduction_") || name.startsWith("hook_");
}

function tryAutoRegister(libPath: string): void {
  if (listProcedures().length > 0 || autoAttempted) return;
  autoAttempted = true;
  const tryLoadModule = (modulePath: string): boolean => {
    try {
      const loadedModule = require(modulePath) as Record<string, unknown>;
      let hasHook = false;
      for (const [name, value] of Object.entries(loadedModule)) {
        if (typeof value !== "function" || !isProcedureName(name)) continue;
        hasHook = true;
        break;
      }
      if (hasHook) return installProcedures(loadedModule) > 0;
      const defaultExport = (loadedModule as Record<string, unknown>).default as
        | Record<string, unknown>
        | undefined;
      if (defaultExport && typeof defaultExport === "object") {
        return installProcedures(defaultExport) > 0;
      }
    } catch {}
    return false;
  };

  // One place: the directory holding the loaded library.
  const baseDirectory = path.dirname(libPath);
  const extensions = ["", ".js", ".ts"];
  for (const extension of extensions) {
    if (tryLoadModule(path.join(baseDirectory, `procedures${extension}`))) return;
  }
}

export function ensureDispatchFor(port: BunPort & FfiPort): void {
  if (!port.supportsDispatch) {
    // No dispatch — installs stay no-ops.
    return;
  }
  tryAutoRegister(port.libraryPath);
  if (installedFor.has(port.libraryPath)) return;
  if (
    typeof port.native.galley_install_js_dispatch_id === "function" &&
    port.procedureNames().length > 0
  ) {
    installIdDispatch(port);
  } else {
    installNameDispatch(port);
  }
  installedFor.add(port.libraryPath);
}

function installIdDispatch(port: BunPort & FfiPort): void {
  if (dispatchIdCallback === null) {
    // Integer hook IDs; unknown IDs are silent no-ops.
    const table = port.procedureNames();
    const cb = new JSCallback(
      (id: number, argsPtr: number) => {
        const name = table[id];
        if (name === undefined) return;
        dispatchProcedure(name, argsPtr, port);
      },
      { args: [FFIType.u32, FFIType.ptr], returns: FFIType.void },
    );
    // Prevent GC — the trampoline must stay reachable for the process lifetime.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchIdCallback = cb;
    dispatchIdCallback = cb;
    dispatchIdPointer = cb.ptr;
  }
  try {
    (port.native.galley_install_js_dispatch_id as (callback: number) => void)(
      dispatchIdPointer as number,
    );
  } catch {
    // Missing installer — stays no-op.
  }
}

function installNameDispatch(port: BunPort & FfiPort): void {
  if (dispatchCallback === null) {
    // Callback takes (namePtr, nameLen, argsPtr); nameLen arrives as bigint.
    const cb = new JSCallback(
      (namePtr: number, nameLen: bigint, argsPtr: number) => {
        if (!namePtr) return;
        let name: string;
        try {
          const bytes = toArrayBuffer(namePtr, 0, Number(nameLen)) as ArrayBuffer;
          name = textDecoder.decode(bytes);
        } catch (e) {
          console.error("galley procedure dispatch: failed to decode name", e);
          return;
        }
        dispatchProcedure(name, argsPtr, port);
      },
      { args: [FFIType.ptr, FFIType.u64, FFIType.ptr], returns: FFIType.void },
    );
    // Prevent GC — the trampoline must stay reachable for the process lifetime.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchCallback = cb;
    dispatchCallback = cb;
    dispatchPointer = cb.ptr;
  }
  try {
    port.native.galley_install_js_dispatch(dispatchPointer as number);
  } catch {
    // Missing installer — stays no-op.
  }
}
