/**
 * Bun procedure-dispatch installer.
 *
 * Owns the `JSCallback` that the shared JS shim
 * (`galley_install_js_dispatch`, generated by `galley-js-core/build/shim.mjs`)
 * forwards every parser hook through, plus the `require()`-based auto-scan
 * of `procedures.*` in the language directory (Bun loads TypeScript
 * synchronously, like Node). The registry and the decoded-name dispatcher
 * live in the core; this module only bridges the native boundary.
 */

import { createRequire } from "node:module";
import * as path from "node:path";
import process from "node:process";
import { JSCallback, FFIType, toArrayBuffer } from "bun:ffi";

import { dispatchProcedure, installProcedures, listProcedures } from "galley-js-core";
import type { FfiPort } from "galley-js-core";
import type { BunPort } from "./ffi.js";

const require = createRequire(import.meta.url);
const textDecoder = new TextDecoder();

// Held to prevent GC of the callback; installed per library path.
let dispatchCallback: unknown = null;
let dispatchPointer: number | null = null;
const installedFor = new Set<string>();
let autoAttempted = false;

function isProcedureName(name: string): boolean {
  return name === "reduction" || name.startsWith("reduction_") || name.startsWith("hook_");
}

function tryAutoRegister(libPath: string): void {
  if (listProcedures().length > 0 || autoAttempted) return;
  autoAttempted = true;
  const tryLoadModule = (modulePath: string): boolean => {
    try {
      const loadedModule = require(modulePath) as Record<string, unknown>;
      let hasHook = false;
      for (const [name, value] of Object.entries(loadedModule)) {
        if (typeof value !== "function" || !isProcedureName(name)) continue;
        hasHook = true;
        break;
      }
      if (hasHook) return installProcedures(loadedModule) > 0;
      const defaultExport = (loadedModule as Record<string, unknown>).default as
        | Record<string, unknown>
        | undefined;
      if (defaultExport && typeof defaultExport === "object") {
        return installProcedures(defaultExport) > 0;
      }
    } catch {}
    return false;
  };

  const candidateBaseDirectories: string[] = [];
  try {
    candidateBaseDirectories.push(path.dirname(libPath));
  } catch {}
  candidateBaseDirectories.push(process.cwd());
  try {
    const entryFile = process.argv[1];
    if (entryFile) {
      const entryDirectory = path.dirname(path.resolve(entryFile));
      if (!candidateBaseDirectories.includes(entryDirectory)) {
        candidateBaseDirectories.push(entryDirectory);
      }
    }
  } catch {}

  const extensions = ["", ".js", ".ts"];
  for (const baseDirectory of candidateBaseDirectories) {
    for (const extension of extensions) {
      const candidatePath = path.join(baseDirectory, `procedures${extension}`);
      if (tryLoadModule(candidatePath)) return;
    }
  }
}

export function ensureDispatchFor(port: BunPort & FfiPort): void {
  if (!port.supportsDispatch) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  tryAutoRegister(port.libraryPath);
  if (installedFor.has(port.libraryPath)) return;
  if (dispatchCallback === null) {
    // Signature mirrors Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void.
    // Note: usize arrives as bigint in callbacks.
    const cb = new JSCallback(
      (namePtr: number, nameLen: bigint, argsPtr: number) => {
        if (!namePtr) return;
        let name: string;
        try {
          const bytes = toArrayBuffer(namePtr, 0, Number(nameLen)) as ArrayBuffer;
          name = textDecoder.decode(bytes);
        } catch (e) {
          console.error("galley procedure dispatch: failed to decode name", e);
          return;
        }
        dispatchProcedure(name, argsPtr, port);
      },
      { args: [FFIType.ptr, FFIType.u64, FFIType.ptr], returns: FFIType.void },
    );
    // Prevent GC — the trampoline must stay reachable for the process lifetime.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchCallback = cb;
    dispatchCallback = cb;
    dispatchPointer = cb.ptr;
  }
  try {
    port.native.galley_install_js_dispatch(dispatchPointer as number);
  } catch {
    // Installer resolution is lazy on some runtimes; a missing installer
    // means a C-procedures library — installs stay no-ops.
  }
  installedFor.add(port.libraryPath);
}
