const std = @import("std");
const common = @import("build/common.zig");

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const clap = b.dependency("clap", .{});

    const core = common.addCoreModules(b, target, optimize);
    _ = common.addGalleyCli(b, target, optimize, core, .{
        .install_default = true,
        .add_galley_step = true,
    });

    const test_filter_opt = b.option([]const []const u8, "test-filter", "Skip tests that do not match any filter") orelse &.{};
    common.addDelegatedTestStep(b, "test", "Run all tests (generator + matrix + parity)", "test", test_filter_opt);
    common.addDelegatedTestStep(
        b,
        "test-generated-parser-matrix",
        "Generate and test parser option matrix",
        "test-generated-parser-matrix",
        &.{},
    );
    common.addDelegatedTestStep(
        b,
        "test-galley-bootstrap-parity",
        "Compare parser output generated by ll-galley and lr-galley",
        "test-galley-bootstrap-parity",
        &.{},
    );

    var dir = try b.build_root.handle.openDir(b.graph.io, common.languages_path, .{ .iterate = true });
    defer dir.close(b.graph.io);

    var walker = try dir.walk(b.allocator);
    defer walker.deinit();
    while (try walker.next(b.graph.io)) |entry| {
        if (entry.kind != .directory and entry.kind != .sym_link) continue;

        inline for ([_][]const u8{ "ll", "lr" }) |parser_type| {
            if (try common.addLanguageParser(
                b,
                target,
                optimize,
                core,
                clap.module("clap"),
                entry.path,
                parser_type,
            )) |parser| {
                try common.addApiBenchmark(b, target, optimize, parser);
            }
        }
    }
}