const std = @import("std");
const common = @import("build/common.zig");
const generated_parser_matrix = @import("build/generated_parser_matrix.zig");

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const clap = b.dependency("clap", .{});

    const generator = common.addGeneratorModules(b, target, optimize);
    const galley_cli = common.addGalleyCli(b, target, optimize, generator, .{
        .install_default = true,
        .add_galley_step = true,
        .include_generate_parser_file = true,
    });
    const generate_parser_file_exe = galley_cli.generate_parser_file_exe.?;

    // Usage: zig build test -Dtest-filter="ll-test-ll"
    // Usage: zig build test -Dtest-filter="generated_parser_api"
    // Long-running samples: zig build test --test-timeout 30m
    const test_filters = b.option([]const []const u8, "test-filter", "Skip tests that do not match any filter") orelse &.{};
    var filtered_test_run_steps: std.ArrayList(*std.Build.Step) = .empty;

    const test_step = b.step("test", "Run all tests (generator + matrix + parity)");
    const generator_tests = b.addTest(.{
        .name = "generator-tests",
        .root_module = generator.galley_generator_mod,
        .filters = test_filters,
    });
    const run_generator_tests = b.addRunArtifact(generator_tests);
    test_step.dependOn(&run_generator_tests.step);
    trackFilteredTestRun(b.allocator, &filtered_test_run_steps, test_filters, &run_generator_tests.step);

    const install_generator_test = b.addInstallArtifact(generator_tests, .{});
    test_step.dependOn(&install_generator_test.step);

    const generated_parser_matrix_step = b.step("test-generated-parser-matrix", "Generate and test parser option matrix");
    try generated_parser_matrix.add(b, generated_parser_matrix_step, .{
        .target = target,
        .optimize = optimize,
        .clap_mod = clap.module("clap"),
        .generator_modules = generator,
        .generate_parser_file_exe = generate_parser_file_exe,
        .filters = test_filters,
        .filtered_test_run_steps = &filtered_test_run_steps,
    });
    test_step.dependOn(generated_parser_matrix_step);

    const ll_galley = (try common.addLanguageParser(b, target, optimize, generator, clap.module("clap"), "galley", "ll")) orelse
        return error.MissingBootstrapGalleyParser;
    const generate_lr_galley_parser = b.addRunArtifact(generate_parser_file_exe);
    generate_lr_galley_parser.stdio = .inherit;
    generate_lr_galley_parser.addArg("--grammar");
    generate_lr_galley_parser.addFileArg(b.path("languages/galley/lr.grm"));
    generate_lr_galley_parser.addArg("--parser-type");
    generate_lr_galley_parser.addArg("lr");
    generate_lr_galley_parser.addArg("--label");
    generate_lr_galley_parser.addArg("lr/galley/bootstrap-parity");
    generate_lr_galley_parser.addArg("--output");
    const lr_galley_parser_path = generate_lr_galley_parser.addOutputFileArg("galley-lr-bootstrap.zig");
    const lr_galley = try common.addLanguageParserFromFile(
        b,
        target,
        optimize,
        generator,
        clap.module("clap"),
        "galley",
        "lr",
        lr_galley_parser_path,
    );

    const parity_step = b.step("test-galley-bootstrap-parity", "Compare parser output generated by ll-galley and lr-galley");
    parity_step.dependOn(ll_galley.build_step);
    parity_step.dependOn(lr_galley.build_step);
    try addGalleyBootstrapParityCase(b, parity_step, ll_galley.exe, lr_galley.exe, "json-ll-no-ast", "languages/json/ll.grm", "_ll-parser.zig", &.{"--no-ast"});
    try addGalleyBootstrapParityCase(b, parity_step, ll_galley.exe, lr_galley.exe, "json-lr-no-ast", "languages/json/lr.grm", "_lr-parser.zig", &.{"--no-ast"});
    try addGalleyBootstrapParityCase(b, parity_step, ll_galley.exe, lr_galley.exe, "json-ll-with-ast", "languages/json/ll.grm", "_ll-parser.zig", &.{"--with-ast"});
    try addGalleyBootstrapParityCase(b, parity_step, ll_galley.exe, lr_galley.exe, "json-lr-with-ast", "languages/json/lr.grm", "_lr-parser.zig", &.{"--with-ast"});
    if (generated_parser_matrix.filterMatchesGalleyParity(b.allocator, test_filters)) {
        test_step.dependOn(parity_step);
    }

    if (test_filters.len > 0) {
        addTestFilterGuard(b, test_step, filtered_test_run_steps.items);
    }
}

fn trackFilteredTestRun(
    allocator: std.mem.Allocator,
    filtered_test_run_steps: *std.ArrayList(*std.Build.Step),
    test_filters: []const []const u8,
    run_step: *std.Build.Step,
) void {
    if (test_filters.len == 0) return;
    filtered_test_run_steps.append(allocator, run_step) catch @panic("OOM");
}

const TestFilterGuard = struct {
    step: std.Build.Step,
    run_steps: []const *std.Build.Step,

    fn create(b: *std.Build, run_steps: []const *std.Build.Step) *TestFilterGuard {
        const guard = b.allocator.create(TestFilterGuard) catch @panic("OOM");
        guard.* = .{
            .step = std.Build.Step.init(.{
                .id = .fail,
                .name = "test-filter-guard",
                .owner = b,
                .makeFn = make,
            }),
            .run_steps = run_steps,
        };
        return guard;
    }

    fn make(step: *std.Build.Step, options: std.Build.Step.MakeOptions) !void {
        _ = options;
        const guard: *TestFilterGuard = @fieldParentPtr("step", step);

        var total_ran: u32 = 0;
        for (guard.run_steps) |run_step| {
            total_ran += run_step.test_results.test_count;
        }
        if (total_ran == 0) {
            try step.result_error_msgs.append(
                step.owner.allocator,
                "no tests matched -Dtest-filter; nothing was run",
            );
            return error.MakeFailed;
        }
    }
};

fn addTestFilterGuard(
    b: *std.Build,
    test_step: *std.Build.Step,
    run_steps: []const *std.Build.Step,
) void {
    const guard = TestFilterGuard.create(b, run_steps);
    for (run_steps) |run_step| {
        guard.step.dependOn(run_step);
    }
    test_step.dependOn(&guard.step);
}

fn addGalleyBootstrapParityCase(
    b: *std.Build,
    parity_step: *std.Build.Step,
    ll_galley_exe: *std.Build.Step.Compile,
    lr_galley_exe: *std.Build.Step.Compile,
    name: []const u8,
    grammar_path: []const u8,
    output_name: []const u8,
    options: []const []const u8,
) !void {
    const base_dir = try std.fs.path.join(b.allocator, &.{ ".zig-cache", "galley-bootstrap-parity", name });
    const ll_dir = try std.fs.path.join(b.allocator, &.{ base_dir, "ll" });
    const lr_dir = try std.fs.path.join(b.allocator, &.{ base_dir, "lr" });
    const grammar_name = std.fs.path.basename(grammar_path);
    const ll_input = try std.fs.path.join(b.allocator, &.{ ll_dir, grammar_name });
    const lr_input = try std.fs.path.join(b.allocator, &.{ lr_dir, grammar_name });
    const ll_output = try std.fs.path.join(b.allocator, &.{ ll_dir, output_name });
    const lr_output = try std.fs.path.join(b.allocator, &.{ lr_dir, output_name });

    const setup = b.addSystemCommand(&.{ "mkdir", "-p", ll_dir, lr_dir });
    setup.has_side_effects = true;

    const copy_ll_input = b.addSystemCommand(&.{ "cp", grammar_path, ll_input });
    copy_ll_input.has_side_effects = true;
    copy_ll_input.step.dependOn(&setup.step);

    const copy_lr_input = b.addSystemCommand(&.{ "cp", grammar_path, lr_input });
    copy_lr_input.has_side_effects = true;
    copy_lr_input.step.dependOn(&setup.step);

    const run_ll_galley = b.addRunArtifact(ll_galley_exe);
    run_ll_galley.has_side_effects = true;
    run_ll_galley.addArg(ll_input);
    run_ll_galley.addArgs(options);
    run_ll_galley.step.dependOn(&copy_ll_input.step);

    const run_lr_galley = b.addRunArtifact(lr_galley_exe);
    run_lr_galley.has_side_effects = true;
    run_lr_galley.addArg(lr_input);
    run_lr_galley.addArgs(options);
    run_lr_galley.step.dependOn(&copy_lr_input.step);

    const compare_outputs = b.addSystemCommand(&.{ "diff", "-u", ll_output, lr_output });
    compare_outputs.has_side_effects = true;
    compare_outputs.step.dependOn(&run_ll_galley.step);
    compare_outputs.step.dependOn(&run_lr_galley.step);
    parity_step.dependOn(&compare_outputs.step);
}
