// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C: each takes the hook's session and the
// ticket of its call, and is called directly.
const root = @import("galley");
pub const Payload = struct {};

pub fn reduction(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction" }));
}
pub fn reduction_Value(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Value" }));
}
pub fn reduction_ObjectMembers(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ObjectMembers" }));
}
pub fn reduction_ArrayMembers(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ArrayMembers" }));
}
pub fn reduction_IntegerNumber(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_IntegerNumber" }));
}
pub fn reduction_FloatTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_FloatTail" }));
}
pub fn reduction_ObjectMembersTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ObjectMembersTail" }));
}
pub fn reduction_ArrayMembersTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ArrayMembersTail" }));
}
pub fn hook_countKey(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countKey" }));
}
pub fn hook_countObject(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countObject" }));
}
pub fn hook_countArray(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countArray" }));
}
pub fn hook_countNumber(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countNumber" }));
}
pub fn hook_countString(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countString" }));
}
pub fn hook_countNull(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countNull" }));
}
pub fn hook_countBoolean(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_countBoolean" }));
}
