/**
 * Deno procedure-dispatch installer.
 *
 * Owns the `UnsafeCallback` that the shared JS shim
 * (`galley_install_js_dispatch_id`, generated by `@sanbus/galley-core/build/shim.mjs`)
 * forwards every parser hook through. The registry and the ID-to-name
 * dispatcher live in the core; this module only bridges the native
 * boundary. Unlike Node there is no auto-scan: Deno consumers register
 * hooks explicitly (`installProcedures(await import("./procedures.ts"))`).
 * Libraries that predate integer hook IDs still export the name-carrying
 * `galley_install_js_dispatch`, used as a fallback.
 */

import { dispatchProcedure } from "@sanbus/galley-core";
import type { FfiPort } from "@sanbus/galley-core";
import type { DenoPort } from "./ffi.ts";

const textDecoder = new TextDecoder();

// Held to prevent GC of the callbacks; installed per library path.
// ID and name paths keep separate slots: their signatures differ.
let dispatchIdCallback: unknown = null;
let dispatchIdPointer: Deno.PointerValue | null = null;
let dispatchCallback: unknown = null;
let dispatchPointer: Deno.PointerValue | null = null;
const installedFor = new Set<string>();

export function ensureDispatchFor(port: DenoPort & FfiPort): void {
  if (!port.supportsDispatch) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  if (installedFor.has(port.libraryPath)) return;
  if (
    typeof port.native.galley_install_js_dispatch_id === "function" &&
    port.procedureNames().length > 0
  ) {
    installIdDispatch(port);
  } else {
    installNameDispatch(port);
  }
  installedFor.add(port.libraryPath);
}

function installIdDispatch(port: DenoPort & FfiPort): void {
  if (dispatchIdCallback === null) {
    // Integer hook IDs: no string copy or decode on the hot path. The table
    // is fixed per library build; unknown IDs are silent no-ops.
    const table = port.procedureNames();
    const cb = new Deno.UnsafeCallback(
      { parameters: ["u32", "pointer"], result: "void" },
      (id, argsPtr) => {
        const name = table[id as number];
        if (name === undefined) return;
        dispatchProcedure(name, argsPtr, port);
      },
    );
    // Prevent GC — the trampoline must stay reachable for the process lifetime.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchIdCallback = cb;
    dispatchIdCallback = cb;
    dispatchIdPointer = cb.pointer;
  }
  (port.native.galley_install_js_dispatch_id as (callback: Deno.PointerValue) => void)(
    dispatchIdPointer as Deno.PointerValue,
  );
}

function installNameDispatch(port: DenoPort & FfiPort): void {
  if (dispatchCallback === null) {
    // Signature mirrors Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void.
    const cb = new Deno.UnsafeCallback(
      { parameters: ["pointer", "usize", "pointer"], result: "void" },
      (namePtr, nameLen, argsPtr) => {
        if (namePtr === null) return;
        let name: string;
        try {
          const bytes = new Deno.UnsafePointerView(namePtr).getArrayBuffer(Number(nameLen)).slice(0);
          name = textDecoder.decode(bytes);
        } catch (e) {
          console.error("galley procedure dispatch: failed to decode name", e);
          return;
        }
        dispatchProcedure(name, argsPtr, port);
      },
    );
    // Prevent GC — the trampoline must stay reachable for the process lifetime.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchCallback = cb;
    dispatchCallback = cb;
    dispatchPointer = cb.pointer;
  }
  port.native.galley_install_js_dispatch(dispatchPointer as Deno.PointerValue);
}
