/**
 * Deno procedure-dispatch installer.
 *
 * Owns the `UnsafeCallback` that the shared JS shim
 * (`galley_install_js_dispatch`, generated by `galley-js-core/build/shim.mjs`)
 * forwards every parser hook through. The registry and the decoded-name
 * dispatcher live in the core; this module only bridges the native
 * boundary. Unlike Node there is no auto-scan: Deno consumers register
 * hooks explicitly (`installProcedures(await import("./procedures.ts"))`).
 */

import { dispatchProcedure } from "galley-js-core";
import type { FfiPort } from "galley-js-core";
import type { DenoPort } from "./ffi.ts";

const textDecoder = new TextDecoder();

// Held to prevent GC of the callback; installed per library path.
let dispatchCallback: unknown = null;
let dispatchPointer: Deno.PointerValue | null = null;
const installedFor = new Set<string>();

export function ensureDispatchFor(port: DenoPort & FfiPort): void {
  if (!port.supportsDispatch) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  if (installedFor.has(port.libraryPath)) return;
  if (dispatchCallback === null) {
    // Signature mirrors Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void.
    const cb = new Deno.UnsafeCallback(
      { parameters: ["pointer", "usize", "pointer"], result: "void" },
      (namePtr, nameLen, argsPtr) => {
        if (namePtr === null) return;
        let name: string;
        try {
          const bytes = new Deno.UnsafePointerView(namePtr).getArrayBuffer(Number(nameLen)).slice(0);
          name = textDecoder.decode(bytes);
        } catch (e) {
          console.error("galley procedure dispatch: failed to decode name", e);
          return;
        }
        dispatchProcedure(name, argsPtr, port);
      },
    );
    // Prevent GC — the trampoline must stay reachable for the process lifetime.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchCallback = cb;
    dispatchCallback = cb;
    dispatchPointer = cb.pointer;
  }
  port.native.galley_install_js_dispatch(dispatchPointer as Deno.PointerValue);
  installedFor.add(port.libraryPath);
}
