/**
 * Deno procedure-dispatch installer.
 *
 * Owns the `UnsafeCallback` that the shared JS shim
 * (`galley_install_js_dispatch_id`, generated by `@sanbus/galley-core/build/shim.mjs`)
 * forwards every parser hook through. The hook tables live in the core —
 * one per session; this module only bridges the native boundary, with one
 * callback closure per loaded library so two grammars in one process
 * never share a port or a name table. Deno consumers register hooks
 * explicitly (pass `procedures` to the session): there is no synchronous
 * module scan on this runtime. Libraries that predate integer hook IDs
 * still export the name-carrying `galley_install_js_dispatch`, used as a
 * fallback.
 */

import { noteSkippedScan } from "@sanbus/galley-core";
import type { FfiPort } from "@sanbus/galley-core";
import type { DenoPort } from "./ffi.ts";

const textDecoder = new TextDecoder();

// Held to prevent GC of the callbacks; installed per library path.
// ID and name paths keep separate slots: their signatures differ.
// Per-path (not singletons): each closure captures its own library's
// port and name table.
const idCallbacks = new Map<string, unknown>();
const idPointers = new Map<string, Deno.PointerValue>();
const nameCallbacks = new Map<string, unknown>();
const namePointers = new Map<string, Deno.PointerValue>();
const installedFor = new Set<string>();

/**
 * Deno has no synchronous module loader, so there is nothing to scan:
 * always null. Exported for a uniform adapter surface (see the
 * universal loader); Deno sessions take `procedures` explicitly.
 */
export function loadProcedures(_languagePath: string): Record<string, unknown> | null {
  return null;
}

/**
 * File twin of {@link loadProcedures}: still null, for the same reason.
 */
export function loadProceduresForFile(_filePath: string): Record<string, unknown> | null {
  return null;
}

function scanJoin(directory: string, file: string): string {
  return directory.endsWith("/") ? directory + file : `${directory}/${file}`;
}

/**
 * Stat probe for a `procedures` file Deno cannot auto-load: returns the
 * found path, or null. Powers the skipped-scan warning (and the
 * universal loader's); loading itself stays explicit.
 */
function probeProceduresFile(directory: string): string | null {
  for (const file of ["procedures", "procedures.js", "procedures.ts"]) {
    const candidate = scanJoin(directory, file);
    try {
      Deno.statSync(candidate);
      return candidate;
    } catch {
      // Absent or unreadable: try the next name.
    }
  }
  return null;
}

/** Procedures file in a language directory, if one is there. */
export function findProceduresFile(directory: string): string | null {
  return probeProceduresFile(directory);
}

/** Procedures file beside an explicit artifact file, if one is there. */
export function findProceduresFileForFile(filePath: string): string | null {
  const slash = filePath.lastIndexOf("/");
  return probeProceduresFile(slash < 0 ? "." : filePath.slice(0, slash) || "/");
}

/** Warn for `Session.fromDirectory` without explicit `procedures`. */
export function warnIfProceduresSkipped(directory: string, explicit: unknown): void {
  noteSkippedScan(findProceduresFile(directory), explicit);
}

/** Warn for `Session.fromFile` without explicit `procedures`. */
export function warnIfProceduresSkippedForFile(filePath: string, explicit: unknown): void {
  noteSkippedScan(findProceduresFileForFile(filePath), explicit);
}

export function ensureDispatchFor(port: DenoPort & FfiPort): void {
  if (!port.supportsDispatch) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  if (installedFor.has(port.libraryPath)) return;
  if (
    typeof port.native.galley_install_js_dispatch_id === "function" &&
    port.procedureNames().length > 0
  ) {
    installIdDispatch(port);
  } else {
    installNameDispatch(port);
  }
  installedFor.add(port.libraryPath);
}

function installIdDispatch(port: DenoPort & FfiPort): void {
  // Integer hook IDs: no string copy or decode on the hot path. The table
  // is fixed per library build; unknown IDs are silent no-ops.
  const table = port.procedureNames();
  const cb = new Deno.UnsafeCallback(
    { parameters: ["u32", "pointer"], result: "void" },
    (id, argsPtr) => {
      const name = table[id as number];
      if (name === undefined) return;
      port.activeDispatch?.(name, argsPtr);
    },
  );
  // Prevent GC — the trampoline must stay reachable for the process lifetime.
  idCallbacks.set(port.libraryPath, cb);
  const pointer = cb.pointer;
  idPointers.set(port.libraryPath, pointer);
  (port.native.galley_install_js_dispatch_id as (callback: Deno.PointerValue) => void)(pointer);
}

function installNameDispatch(port: DenoPort & FfiPort): void {
  // Signature mirrors Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void.
  const cb = new Deno.UnsafeCallback(
    { parameters: ["pointer", "usize", "pointer"], result: "void" },
    (namePtr, nameLen, argsPtr) => {
      if (namePtr === null) return;
      let name: string;
      try {
        const bytes = new Deno.UnsafePointerView(namePtr).getArrayBuffer(Number(nameLen)).slice(0);
        name = textDecoder.decode(bytes);
      } catch (e) {
        console.error("galley procedure dispatch: failed to decode name", e);
        return;
      }
      port.activeDispatch?.(name, argsPtr);
    },
  );
  // Prevent GC — the trampoline must stay reachable for the process lifetime.
  nameCallbacks.set(port.libraryPath, cb);
  const pointer = cb.pointer;
  namePointers.set(port.libraryPath, pointer);
  port.native.galley_install_js_dispatch(pointer);
}
