/**
 * Node procedure-dispatch installer.
 *
 * Owns the koffi callback that the shared JS shim
 * (`galley_install_js_dispatch_id`, generated by `@sanbus/galley-core/build/shim.mjs`)
 * forwards every parser hook through, plus the `require()`-based auto-scan
 * of `procedures.*` in the language directory. The registry and the
 * ID-to-name dispatcher live in the core; this module only bridges the
 * native boundary. Libraries that predate integer hook IDs still export
 * the name-carrying `galley_install_js_dispatch`, used as a fallback.
 */

import { createRequire } from "node:module";
import * as path from "node:path";
const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-require-imports
const koffi = require("koffi") as typeof import("koffi");

import { dispatchProcedure, installProcedures, listProcedures } from "@sanbus/galley-core";
import type { FfiPort } from "@sanbus/galley-core";
import { copyStringBytes, type GalleyFFI } from "./ffi.ts";

// Held to prevent GC of the koffi callbacks; installed per library path.
// ID and name paths keep separate slots: their signatures differ.
let dispatchIdCallback: unknown = null;
let dispatchCallback: unknown = null;
const installedFor = new Set<string>();
let autoAttempted = false;

function isProcedureName(name: string): boolean {
  return name === "reduction" || name.startsWith("reduction_") || name.startsWith("hook_");
}

function tryAutoRegister(foreignInterface: GalleyFFI): void {
  if (listProcedures().length > 0 || autoAttempted) return;
  autoAttempted = true;
  const tryLoadModule = (modulePath: string): boolean => {
    try {
      const loadedModule = require(modulePath) as Record<string, unknown>;
      let hasHook = false;
      for (const [name, value] of Object.entries(loadedModule)) {
        if (typeof value !== "function" || !isProcedureName(name)) continue;
        hasHook = true;
        break;
      }
      if (hasHook) return installProcedures(loadedModule) > 0;
      const defaultExport = (loadedModule as Record<string, unknown>).default as
        | Record<string, unknown>
        | undefined;
      if (defaultExport && typeof defaultExport === "object") {
        return installProcedures(defaultExport) > 0;
      }
    } catch {}
    return false;
  };

  // One place: the directory holding the loaded library. Anything found
  // there belongs to this grammar; nothing else is even looked at.
  const baseDirectory = path.dirname(foreignInterface.libPath);
  const extensions = ["", ".js", ".ts"];
  for (const extension of extensions) {
    if (tryLoadModule(path.join(baseDirectory, `procedures${extension}`))) return;
  }
}

export function ensureDispatchFor(foreignInterface: GalleyFFI, port: FfiPort): void {
  // Option B: auto — if no explicit hooks yet, try to auto-discover procedures.* in language dir
  tryAutoRegister(foreignInterface);
  const useIds =
    foreignInterface.galley_install_js_dispatch_id !== null &&
    typeof port.procedureNames === "function" &&
    port.procedureNames().length > 0;
  if (!useIds && foreignInterface.galley_install_js_dispatch === null) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  if (installedFor.has(foreignInterface.libPath)) return;
  if (useIds) {
    installIdDispatch(foreignInterface, port);
  } else {
    installNameDispatch(foreignInterface, port);
  }
  installedFor.add(foreignInterface.libPath);
}

function installIdDispatch(foreignInterface: GalleyFFI, port: FfiPort): void {
  if (dispatchIdCallback === null) {
    // Integer hook IDs: no string copy or decode on the hot path. The table
    // is fixed per library build; unknown IDs are silent no-ops.
    const table = port.procedureNames();
    const proto = koffi.proto("void DispatchId(uint32_t id, void *args)");
    const cb = koffi.register((id: unknown, argsPtr: unknown) => {
      const name = table[typeof id === "bigint" ? Number(id) : (id as number)];
      if (name === undefined) return;
      let argsAddr: bigint = 0n;
      if (argsPtr !== null && argsPtr !== undefined) {
        try {
          argsAddr = typeof argsPtr === "bigint" ? (argsPtr as bigint) : BigInt(argsPtr as number);
        } catch {
          argsAddr = 0n;
        }
      }
      dispatchProcedure(name, argsAddr, port);
    }, koffi.pointer(proto));
    // Prevent GC — registered callbacks must stay reachable; koffi holds the
    // trampoline, but we keep the address alive as well.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchIdCallback = cb;
    dispatchIdCallback = cb;
  }
  foreignInterface.galley_install_js_dispatch_id!(dispatchIdCallback);
}

function installNameDispatch(foreignInterface: GalleyFFI, port: FfiPort): void {
  if (dispatchCallback === null) {
    // Create single global dispatcher. Uses registered callback (must persist
    // beyond the installer call, unlike transient callbacks). Signature mirrors
    // Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void — void* for
    // the name pointer keeps it as a raw address with length.
    const proto = koffi.proto("void Dispatch(void *name_ptr, size_t name_len, void *args)");
    const cb = koffi.register((namePtr: unknown, nameLen: unknown, argsPtr: unknown) => {
      let name: string;
      try {
        // Registered callbacks receive pointer values as BigInt (or null).
        const ptrVal: bigint = typeof namePtr === "bigint" ? (namePtr as bigint) : BigInt(namePtr as number);
        const lenVal: bigint | number = typeof nameLen === "bigint" ? (nameLen as bigint) : (nameLen as number);
        name = copyStringBytes(ptrVal as bigint, lenVal as bigint | number);
      } catch (e) {
        console.error("galley procedure dispatch: failed to decode name", e);
        return;
      }
      let argsAddr: bigint = 0n;
      if (argsPtr !== null && argsPtr !== undefined) {
        try {
          argsAddr = typeof argsPtr === "bigint" ? (argsPtr as bigint) : BigInt(argsPtr as number);
        } catch {
          argsAddr = 0n;
        }
      }
      dispatchProcedure(name, argsAddr, port);
    }, koffi.pointer(proto));
    // Prevent GC — registered callbacks must stay reachable; koffi holds the
    // trampoline, but we keep the address alive as well.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchCallback = cb;
    dispatchCallback = cb;
  }
  foreignInterface.galley_install_js_dispatch!(dispatchCallback);
}
