/**
 * Node procedure-dispatch installer.
 *
 * Owns the NAPI callbacks that the shared JS shim
 * (`galley_install_js_dispatch_id`, generated by `@sanbus/galley-core/build/shim.mjs`)
 * forwards every parser hook through, plus the `require()`-based auto-scan
 * of `procedures.*` in the language directory. The registry and the
 * ID-to-name dispatcher live in the core; this module only bridges the
 * native boundary. Libraries that predate integer hook IDs still export
 * the name-carrying `galley_install_js_dispatch`, used as a fallback.
 */

import * as path from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);

import { dispatchProcedure, installProcedures, listProcedures } from "@sanbus/galley-core";
import type { FfiPort } from "@sanbus/galley-core";
import type { GalleyFFI } from "./ffi.ts";

// Held to prevent GC of the installed callbacks; installed per library path.
// The addon also retains them, but the address must stay reachable here too.
// ID and name paths keep separate slots: their signatures differ.
let dispatchIdCallback: ((id: number, args: bigint) => void) | null = null;
let dispatchCallback: ((name: string, args: bigint) => void) | null = null;
const installedFor = new Set<string>();
let autoAttempted = false;

function isProcedureName(name: string): boolean {
  return name === "reduction" || name.startsWith("reduction_") || name.startsWith("hook_");
}

function tryAutoRegister(foreignInterface: GalleyFFI): void {
  if (listProcedures().length > 0 || autoAttempted) return;
  autoAttempted = true;
  const tryLoadModule = (modulePath: string): boolean => {
    try {
      const loadedModule = require(modulePath) as Record<string, unknown>;
      let hasHook = false;
      for (const [name, value] of Object.entries(loadedModule)) {
        if (typeof value !== "function" || !isProcedureName(name)) continue;
        hasHook = true;
        break;
      }
      if (hasHook) return installProcedures(loadedModule) > 0;
      const defaultExport = (loadedModule as Record<string, unknown>).default as
        | Record<string, unknown>
        | undefined;
      if (defaultExport && typeof defaultExport === "object") {
        return installProcedures(defaultExport) > 0;
      }
    } catch {}
    return false;
  };

  // One place: the directory holding the loaded library.
  const baseDirectory = path.dirname(foreignInterface.libPath);
  const extensions = ["", ".js", ".ts"];
  for (const extension of extensions) {
    if (tryLoadModule(path.join(baseDirectory, `procedures${extension}`))) return;
  }
}

export function ensureDispatchFor(foreignInterface: GalleyFFI, port: FfiPort): void {
  tryAutoRegister(foreignInterface);
  const useIds =
    foreignInterface.api.install_id_dispatch !== null &&
    typeof port.procedureNames === "function" &&
    port.procedureNames().length > 0;
  if (!useIds && foreignInterface.api.install_name_dispatch === null) {
    // No dispatch — installs stay no-ops.
    return;
  }
  if (installedFor.has(foreignInterface.libPath)) return;
  if (useIds) {
    installIdDispatch(foreignInterface, port);
  } else {
    installNameDispatch(foreignInterface, port);
  }
  installedFor.add(foreignInterface.libPath);
}

function installIdDispatch(foreignInterface: GalleyFFI, port: FfiPort): void {
  if (dispatchIdCallback === null) {
    // Integer hook IDs; unknown IDs are silent no-ops.
    const table = port.procedureNames();
    dispatchIdCallback = (id: number, args: bigint) => {
      const name = table[id];
      if (name === undefined) return;
      dispatchProcedure(name, args, port);
    };
  }
  foreignInterface.api.install_id_dispatch!(dispatchIdCallback);
}

function installNameDispatch(foreignInterface: GalleyFFI, port: FfiPort): void {
  if (dispatchCallback === null) {
    // The addon decodes the hook name before crossing; the callback gets
    // the string and the raw args address.
    dispatchCallback = (name: string, args: bigint) => {
      dispatchProcedure(name, args, port);
    };
  }
  foreignInterface.api.install_name_dispatch!(dispatchCallback);
}
