/**
 * Node procedure-dispatch installer.
 *
 * Owns the koffi callback that the shared JS shim
 * (`galley_install_js_dispatch`, generated by `galley-js-core/build/shim.mjs`)
 * forwards every parser hook through, plus the `require()`-based auto-scan
 * of `procedures.*` in the language directory. The registry and the
 * decoded-name dispatcher live in the core; this module only bridges the
 * native boundary.
 */

import { createRequire } from "node:module";
import * as path from "node:path";
const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-require-imports
const koffi = require("koffi") as typeof import("koffi");

import { dispatchProcedure, installProcedures, listProcedures } from "galley-js-core";
import type { FfiPort } from "galley-js-core";
import { copyStringBytes, type GalleyFFI } from "./ffi.js";

// Held to prevent GC of the koffi callback; installed per library path.
let dispatchCallback: unknown = null;
const installedFor = new Set<string>();
let autoAttempted = false;

function isProcedureName(name: string): boolean {
  return name === "reduction" || name.startsWith("reduction_") || name.startsWith("hook_");
}

function tryAutoRegister(foreignInterface: GalleyFFI): void {
  if (listProcedures().length > 0 || autoAttempted) return;
  autoAttempted = true;
  const tryLoadModule = (modulePath: string): boolean => {
    try {
      const loadedModule = require(modulePath) as Record<string, unknown>;
      let hasHook = false;
      for (const [name, value] of Object.entries(loadedModule)) {
        if (typeof value !== "function" || !isProcedureName(name)) continue;
        hasHook = true;
        break;
      }
      if (hasHook) return installProcedures(loadedModule) > 0;
      const defaultExport = (loadedModule as Record<string, unknown>).default as
        | Record<string, unknown>
        | undefined;
      if (defaultExport && typeof defaultExport === "object") {
        return installProcedures(defaultExport) > 0;
      }
    } catch {}
    return false;
  };

  // One place: the directory holding the loaded library. Anything found
  // there belongs to this grammar; nothing else is even looked at.
  const baseDirectory = path.dirname(foreignInterface.libPath);
  const extensions = ["", ".js", ".ts"];
  for (const extension of extensions) {
    if (tryLoadModule(path.join(baseDirectory, `procedures${extension}`))) return;
  }
}

export function ensureDispatchFor(foreignInterface: GalleyFFI, port: FfiPort): void {
  if (foreignInterface.galley_install_js_dispatch === null) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  // Option B: auto — if no explicit hooks yet, try to auto-discover procedures.* in language dir
  tryAutoRegister(foreignInterface);
  if (installedFor.has(foreignInterface.libPath)) return;
  if (dispatchCallback === null) {
    // Create single global dispatcher. Uses registered callback (must persist
    // beyond the installer call, unlike transient callbacks). Signature mirrors
    // Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void — void* for
    // the name pointer keeps it as a raw address with length.
    const proto = koffi.proto("void Dispatch(void *name_ptr, size_t name_len, void *args)");
    const cb = koffi.register((namePtr: unknown, nameLen: unknown, argsPtr: unknown) => {
      let name: string;
      try {
        // Registered callbacks receive pointer values as BigInt (or null).
        const ptrVal: bigint = typeof namePtr === "bigint" ? (namePtr as bigint) : BigInt(namePtr as number);
        const lenVal: bigint | number = typeof nameLen === "bigint" ? (nameLen as bigint) : (nameLen as number);
        name = copyStringBytes(ptrVal as bigint, lenVal as bigint | number);
      } catch (e) {
        console.error("galley procedure dispatch: failed to decode name", e);
        return;
      }
      let argsAddr: bigint = 0n;
      if (argsPtr !== null && argsPtr !== undefined) {
        try {
          argsAddr = typeof argsPtr === "bigint" ? (argsPtr as bigint) : BigInt(argsPtr as number);
        } catch {
          argsAddr = 0n;
        }
      }
      dispatchProcedure(name, argsAddr, port);
    }, koffi.pointer(proto));
    // Prevent GC — registered callbacks must stay reachable; koffi holds the
    // trampoline, but we keep the address alive as well.
    (globalThis as unknown as Record<string, unknown>).__galley_js_dispatchCallback = cb;
    dispatchCallback = cb;
  }
  foreignInterface.galley_install_js_dispatch!(dispatchCallback);
  installedFor.add(foreignInterface.libPath);
}
