// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C; they are called directly.
const root = @import("galley");
pub const Payload = struct {};

pub extern fn reduction(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Value(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__OptionalBlank(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_ObjectMembers(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_ArrayMembers(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_IntegerNumber(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_FloatTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__StringContent(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_ObjectMembersTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_ArrayMembersTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__OptionalBlankTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__PositiveIntegerNumberTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__AugmentedStart(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_GenerativeTerminal(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countKey(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countObject(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countArray(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countNumber(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countString(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countNull(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_countBoolean(*root.data_structures.ProcedureArguments) void;
