// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C: each takes the hook's session and the
// ticket of its call, and is called directly.
const root = @import("galley");
pub const Payload = struct {};

pub fn reduction(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction" }));
}
pub fn reduction_Start(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Start" }));
}
pub fn reduction_Rules(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Rules" }));
}
pub fn reduction_Comment(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Comment" }));
}
pub fn reduction_OptionalNewLineMany(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_OptionalNewLineMany" }));
}
pub fn reduction_Rule(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Rule" }));
}
pub fn reduction_RulesTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RulesTail" }));
}
pub fn reduction_NewLine(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_NewLine" }));
}
pub fn reduction_VariableSymbol(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_VariableSymbol" }));
}
pub fn reduction_AnnotationTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_AnnotationTail" }));
}
pub fn reduction_RightHandSides(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RightHandSides" }));
}
pub fn reduction_RightHandSideLine(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RightHandSideLine" }));
}
pub fn reduction_RightHandSide(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RightHandSide" }));
}
pub fn reduction_Symbol(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Symbol" }));
}
pub fn reduction_TerminalSymbol(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_TerminalSymbol" }));
}
pub fn reduction_GenerativeTerminalSymbol(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_GenerativeTerminalSymbol" }));
}
pub fn reduction_UppercaseId(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_UppercaseId" }));
}
pub fn reduction_RawString(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RawString" }));
}
pub fn reduction_SimpleStringContent(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_SimpleStringContent" }));
}
pub fn reduction_RawIndicator(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RawIndicator" }));
}
pub fn reduction_LowercaseId(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_LowercaseId" }));
}
pub fn reduction_GenerativeTerminalExceptions(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_GenerativeTerminalExceptions" }));
}
pub fn reduction_Annotation(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Annotation" }));
}
pub fn reduction_Procedure(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Procedure" }));
}
pub fn reduction_RecoveryPoint(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RecoveryPoint" }));
}
pub fn reduction_VerbatimMarker(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_VerbatimMarker" }));
}
pub fn reduction_CamelCaseId(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_CamelCaseId" }));
}
pub fn reduction_TerminalAndCursor(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_TerminalAndCursor" }));
}
pub fn reduction__Utf8Scalar(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__Utf8Scalar" }));
}
pub fn reduction__Utf8TwoByte(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__Utf8TwoByte" }));
}
pub fn reduction__Utf8ThreeByte(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__Utf8ThreeByte" }));
}
pub fn reduction__Utf8FourByte(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__Utf8FourByte" }));
}
pub fn reduction_ControlCharacter(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_ControlCharacter" }));
}
pub fn reduction_AnyContent(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_AnyContent" }));
}
pub fn reduction_IdTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_IdTail" }));
}
pub fn reduction_CamelCaseIdTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_CamelCaseIdTail" }));
}
pub fn reduction_BlockStart(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BlockStart" }));
}
pub fn reduction_BlockEnd(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_BlockEnd" }));
}
pub fn reduction_CommentLine(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_CommentLine" }));
}
pub fn reduction__AugmentedStart(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction__AugmentedStart" }));
}
pub fn reduction_GenerativeTerminal(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_GenerativeTerminal" }));
}
pub fn reduction_RightHandSides_Tail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_RightHandSides_Tail" }));
}
pub fn reduction_AnyContent_Tail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_AnyContent_Tail" }));
}
pub fn reduction_AnyContent_Tail0(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_AnyContent_Tail0" }));
}
