// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C: each takes the hook's session and the
// ticket of its call, and is called directly.
const root = @import("galley");
pub const Payload = struct {};

pub fn reduction(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction" }));
}
pub fn reduction_Document(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Document" }));
}
pub fn reduction_PairList(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_PairList" }));
}
pub fn reduction_Pair(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Pair" }));
}
pub fn reduction_PairListTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_PairListTail" }));
}
pub fn reduction_Key(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Key" }));
}
pub fn reduction_Number(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_Number" }));
}
pub fn reduction_KeyTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_KeyTail" }));
}
pub fn reduction_NumberTail(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "reduction_NumberTail" }));
}
pub fn hook_print(args: *root.data_structures.ProcedureArguments) void {
    root.data_structures.host_hooks.callCompiled(args, @extern(*const fn (?*anyopaque, u64) callconv(.c) void, .{ .name = "hook_print" }));
}
