// Auto-generated by Galley — edit your procedures C file instead.
// Implement these functions in C; they are called directly.
const root = @import("galley");
pub const Payload = struct {};

pub extern fn reduction(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Document(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_PairList(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Pair(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_PairListTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Key(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_Number(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_KeyTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_NumberTail(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction__AugmentedStart(*root.data_structures.ProcedureArguments) void;
pub extern fn reduction_GenerativeTerminal(*root.data_structures.ProcedureArguments) void;
pub extern fn hook_print(*root.data_structures.ProcedureArguments) void;
