/**
 * Host-language procedure registry for the TypeScript bindings.
 *
 * Mirrors `bindings/python/_galley.c:42` (global dict + `py_dispatch_impl`)
 * and `bindings/go/cmd/galley/main.go:281` (per-slot dispatch). The Zig shim
 * (`procedures_typescript.zig`, generated by `bindings/typescript/build.mjs`)
 * holds a single nullable `js_dispatch_target` that this module installs via
 * `galley_install_typescript_dispatch`. Each parser hook
 * (`reduction`, `reduction_<Var>`, `hook_<name>`) dispatches through that
 * single callback; unregistered names are silent no-ops.
 *
 * The opaque `ProcedureArguments*` is passed as a `bigint` address, matching
 * Python's `int` and Go's `unsafe.Pointer`. Hooks may ignore it or pass it
 * to future helpers; initial examples only emit side effects.
 */

import { createRequire } from "node:module";
import * as path from "node:path";
const require = createRequire(import.meta.url);
// eslint-disable-next-line @typescript-eslint/no-require-imports
const koffi = require("koffi") as typeof import("koffi");

import { copyStringBytes, loadLibrary, type GalleyFFI } from "./ffi.js";

type HookFn = (args: bigint) => void;

const registry = new Map<string, HookFn>();

// Held to prevent GC of the koffi callback; installed per library path.
let dispatchCallback: unknown = null;
const installedFor = new Set<string>();
let autoAttempted = false;

function isProcedureName(name: string): boolean {
  return name === "reduction" || name.startsWith("reduction_") || name.startsWith("hook_");
}

function tryAutoRegister(foreignInterface: GalleyFFI): void {
  if (registry.size > 0 || autoAttempted) return;
  autoAttempted = true;
  const tryLoadModule = (modulePath: string): boolean => {
    try {
      const loadedModule = require(modulePath) as Record<string, unknown>;
      let installedCount = 0;
      for (const [name, value] of Object.entries(loadedModule)) {
        if (typeof value !== "function" || !isProcedureName(name)) continue;
        registry.set(name, value as HookFn);
        installedCount++;
      }
      if (installedCount > 0) return true;
      const defaultExport = (loadedModule as Record<string, unknown>).default as
        | Record<string, unknown>
        | undefined;
      if (defaultExport && typeof defaultExport === "object") {
        let defaultInstalledCount = 0;
        for (const [name, value] of Object.entries(defaultExport)) {
          if (typeof value !== "function" || !isProcedureName(name)) continue;
          registry.set(name, value as HookFn);
          defaultInstalledCount++;
        }
        if (defaultInstalledCount > 0) return true;
      }
    } catch {}
    return false;
  };

  const candidateBaseDirectories: string[] = [];
  try {
    const libraryDirectory = path.dirname(foreignInterface.libPath);
    candidateBaseDirectories.push(libraryDirectory);
  } catch {}
  candidateBaseDirectories.push(process.cwd());
  try {
    const entryFile = process.argv[1];
    if (entryFile) {
      const entryDirectory = path.dirname(path.resolve(entryFile));
      if (!candidateBaseDirectories.includes(entryDirectory)) {
        candidateBaseDirectories.push(entryDirectory);
      }
    }
  } catch {}

  const extensions = ["", ".js", ".ts"];
  for (const baseDirectory of candidateBaseDirectories) {
    for (const extension of extensions) {
      const candidatePath = path.join(baseDirectory, `procedures${extension}`);
      if (tryLoadModule(candidatePath)) return;
    }
  }
}

export function ensureDispatchFor(foreignInterface: GalleyFFI): void {
  if (foreignInterface.galley_install_typescript_dispatch === null) {
    // Library was built for C procedures (no shim); installs will be no-ops.
    return;
  }
  // Option B: auto — if no explicit hooks yet, try to auto-discover procedures.* in language dir
  tryAutoRegister(foreignInterface);
  if (installedFor.has(foreignInterface.libPath)) return;
  if (dispatchCallback === null) {
    // Create single global dispatcher. Uses registered callback (must persist
    // beyond the installer call, unlike transient callbacks). Signature mirrors
    // Zig: fn([*]const u8, usize, ?*anyopaque) callconv(.c) void — void* for
    // the name pointer keeps it as a raw address with length.
    const proto = koffi.proto("void Dispatch(void *name_ptr, size_t name_len, void *args)");
    const cb = koffi.register((namePtr: unknown, nameLen: unknown, argsPtr: unknown) => {
      let name: string;
      try {
        // Registered callbacks receive pointer values as BigInt (or null).
        const ptrVal: bigint = typeof namePtr === "bigint" ? (namePtr as bigint) : BigInt(namePtr as number);
        const lenVal: bigint | number = typeof nameLen === "bigint" ? (nameLen as bigint) : (nameLen as number);
        name = copyStringBytes(ptrVal as bigint, lenVal as bigint | number);
      } catch (e) {
        console.error("galley procedure dispatch: failed to decode name", e);
        return;
      }
      const fn = registry.get(name);
      if (!fn) return;
      let argsAddr: bigint = 0n;
      if (argsPtr !== null && argsPtr !== undefined) {
        try {
          argsAddr = typeof argsPtr === "bigint" ? (argsPtr as bigint) : BigInt(argsPtr as number);
        } catch {
          argsAddr = 0n;
        }
      }
      try {
        if (fn.length === 0) {
          (fn as () => void)();
        } else {
          (fn as HookFn)(argsAddr);
        }
      } catch (err) {
        // Mirror Python's PyErr_Print: log and continue parsing.
        console.error(`galley procedure ${name} threw:`, err);
      }
    }, koffi.pointer(proto));
    // Prevent GC — registered callbacks must stay reachable; koffi holds the
    // trampoline, but we keep the address alive as well.
    (globalThis as unknown as Record<string, unknown>).__galley_ts_dispatchCallback = cb;
    dispatchCallback = cb;
  }
  foreignInterface.galley_install_typescript_dispatch!(dispatchCallback);
  installedFor.add(foreignInterface.libPath);
}

function ensureInstalled(): ReturnType<typeof loadLibrary> | null {
  const ffi = loadLibrary();
  if (ffi.galley_install_typescript_dispatch === null) return null;
  ensureDispatchFor(ffi);
  return ffi;
}

/**
 * Installs a single procedure hook. `fn` may be `(args: bigint)=>void` or
 * `()=>void`; `args` is the opaque `ProcedureArguments*` address.
 * Overwrites any existing entry for `name`.
 */
export function installProcedure(name: string, fn: HookFn | (() => void)): void {
  if (typeof name !== "string" || name.length === 0) throw new TypeError("procedure name must be non-empty string");
  if (typeof fn !== "function") throw new TypeError("procedure must be a function");
  // Ensure the dispatch is installed before mutating the map so the first
  // parse after registration already dispatches.
  ensureInstalled();
  registry.set(name, fn as HookFn);
}

/**
 * Scans `module` for exported procedure hooks (`reduction`, `reduction_*`,
 * `hook_*`) and registers each function. Returns the number installed.
 * Mirrors `bindings/python/_galley.c:2339` `install_procedures`.
 */
export function installProcedures(module: Record<string, unknown>): number {
  if (module === null || typeof module !== "object") throw new TypeError("module must be an object");
  let count = 0;
  // Ensure once before loop; avoids repeated loadLibrary lookups.
  ensureInstalled();
  for (const [name, value] of Object.entries(module)) {
    if (typeof value !== "function") continue;
    if (!isProcedureName(name)) continue;
    registry.set(name, value as HookFn);
    count++;
  }
  // Also check default export interop for ESM `export default { ... }`?
  // Python's dict scan covers module __dict__ only; keep explicit.
  return count;
}

/** Removes all registered hooks; subsequent parses will be no-ops. */
export function clearProcedures(): void {
  registry.clear();
}

/** Returns currently registered procedure names. */
export function listProcedures(): string[] {
  return [...registry.keys()];
}
