const std = @import("std");
const common = @import("generator_common");

pub fn emitRecoveryOffsetFunction(writer: *std.Io.Writer, function_name: []const u8) !void {
    try writer.print(
        \\fn {s}(context: *data_structures.Context, candidates: []const []const u8, start: usize) !?usize {{
        \\    const lookahead = try context.recoveryLookahead();
        \\    if (candidates.len == 0) {{
        \\        if (lookahead[0] == 0) context.finishSyntaxRecovery();
        \\        return null;
        \\    }}
        \\    const upper = @min(context.recoveryWindow(), lookahead.len);
        \\    var offset = start;
        \\    while (offset < upper) : (offset += 1) {{
        \\        for (candidates) |candidate| {{
        \\            if (candidate.len <= lookahead.len - offset and std.mem.eql(u8, lookahead[offset..][0..candidate.len], candidate)) {{
        \\                context.finishSyntaxRecovery();
        \\                return offset;
        \\            }}
        \\        }}
        \\        if (lookahead[offset] == 0) break;
        \\    }}
        \\    if (lookahead[0] == 0) context.finishSyntaxRecovery();
        \\    return null;
        \\}}
        \\
    , .{function_name});
}

pub fn emitRecoveryPoints(writer: *std.Io.Writer, points: []const common.RecoveryPoint) !void {
    try writer.writeAll("&[_]root.SyntaxRecoveryPoint{");
    for (points, 0..) |point, index| {
        if (index != 0) try writer.writeAll(", ");
        try writer.writeAll(".{ .terminal = ");
        try common.emitStringLiteral(writer, point.terminal);
        try writer.print(", .@\"resume\" = .{s} }}", .{@tagName(point.@"resume")});
    }
    try writer.writeByte('}');
}

/// Emits the standalone customization file from completed diagnostic plans.
pub fn emitErrorMessageFile(
    writer: *std.Io.Writer,
    parser_label: []const u8,
    specs: []const common.ErrorMessageSpec,
) !void {
    try writer.print(
        \\const root = @import("galley");
        \\
        \\// Default {s} syntax error messages generated by Galley.
        \\// Edit any function body to customize that error site.
        \\
        \\
    , .{parser_label});
    for (specs) |spec| {
        try writer.print(
            \\pub fn {s}(args: root.SyntaxErrorMessageArgs) ![]const u8 {{
            \\    return try root.renderParseDiagnostic(args.allocator, args.diagnostic, args.style);
            \\}}
            \\
            \\
        , .{spec.name});
    }
}

pub fn emitParserMetadata(
    writer: *std.Io.Writer,
    parser_type: []const u8,
    options: common.Options,
    uses_explicit_recovery: bool,
    longest_terminal_length: usize,
) !void {
    try writer.print(
        \\
        \\pub const parser_type = data_structures.ParserType.{s};
        \\pub const ErrorRecoveryMode = enum {{ disabled, automatic, explicit }};
        \\pub const is_ast_enabled = {};
        \\pub const are_procedures_enabled = {};
        \\pub const is_error_recovery_enabled = {};
        \\pub const error_recovery_mode: ErrorRecoveryMode = .{s};
        \\pub const is_position_tracking_enabled = {s};
        \\pub const is_input_streaming_enabled = {};
        \\pub const longest_terminal_length = {d};
        \\
        \\
    , .{
        parser_type,
        options.with_ast,
        options.with_procedures,
        options.with_error_recovery,
        if (!options.with_error_recovery) "disabled" else if (uses_explicit_recovery) "explicit" else "automatic",
        if (options.with_position_tracking) |enabled| if (enabled) "true" else "false" else "builtin.mode != .ReleaseFast",
        options.with_input_streaming,
        longest_terminal_length,
    });
}

/// Emits the grammar metadata shared by LL and LR generated parsers.
///
/// The function deliberately preserves the existing table order and source
/// spelling; backends provide only their completed, typed grammar plan.
pub fn emitGrammarTables(
    writer: *std.Io.Writer,
    symbols: []const common.Symbol,
    variables: []const usize,
    rules: []const common.Rule,
) !void {
    try writer.writeAll("pub const symbols = &[_][]const u8{\n");
    for (symbols, 0..) |symbol, index| {
        try writer.writeAll("    ");
        try common.emitStringLiteral(writer, symbol.id);
        try writer.print(", // {d}\n", .{index});
    }
    try writer.writeAll("};\n\npub const is_terminal = &[_]bool{\n");
    for (symbols) |symbol| try writer.print("    {},\n", .{symbol.kind != .variable});
    try writer.writeAll("};\n\npub const is_generative_terminal = &[_]bool{\n");
    for (symbols) |symbol| try writer.print("    {},\n", .{symbol.kind == .generative_terminal});
    try writer.writeAll("};\n\npub const variables = &[_][]const u8{\n");
    for (variables) |symbol_index| {
        try writer.writeAll("    ");
        try common.emitStringLiteral(writer, symbols[symbol_index].id);
        try writer.writeAll(",\n");
    }
    try writer.writeAll("};\n\npub const symbol_by_variable = &[_]usize{\n");
    for (variables) |symbol_index| try writer.print("    {d},\n", .{symbol_index});
    try writer.writeAll("};\n\npub const rules = &[_]data_structures.Rule{\n");
    for (rules) |rule| {
        const variable_index = variableIndex(variables, rule.header);
        try writer.print("    data_structures.Rule{{ .header = {d}, .right_hand_side = &[_]u16{{", .{variable_index});
        if (rule.rhs.items.len > 1) try writer.writeByte(' ');
        for (rule.rhs.items, 0..) |symbol_index, i| {
            if (i != 0) try writer.writeAll(", ");
            try writer.print("{d}", .{symbol_index});
        }
        if (rule.rhs.items.len > 1) try writer.writeByte(' ');
        try writer.writeAll("}, .right_hand_side_index = ");
        try common.emitStringLiteral(writer, rule.rhs_index);
        try writer.writeAll(" }, // ");
        try writer.writeAll(symbols[rule.header].id);
        try writer.writeByte('\n');
    }
    try writer.writeAll("};\n\n");
}

fn variableIndex(variables: []const usize, symbol_index: usize) usize {
    for (variables, 0..) |candidate, index| {
        if (candidate == symbol_index) return index;
    }
    unreachable;
}
